### ISSUE TITLE
Not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by blackbart420** [shalldie/vscode-background#382]
Hello @shalldie !
I use your awesome extension on archlinux without problem but it seems it does not work on ubuntu.

First I get this message when VSCode starts:

`EROFS: read-only file system, access '/snap/code/122/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.css'`

I click on "Retry with sudo/admin" like I usually do on archlinux but then I get this error:

`Command failed: cd "/home/nicolas"; "/usr/bin/pkexec" --disable-internal-agent /bin/bash -c "echo SUDOPROMPT; mv -f \"/tmp/vscode-background-9511b598-9309-4bd1-b459-92cb5d6ad474.css\" \"/snap/code/122/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.css\"" mv: échec de déplacement interpériphérique de '/tmp/vscode-background-9511b598-9309-4bd1-b459-92cb5d6ad474.css' vers '/snap/code/122/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.css' ; impossible de supprimer la cible: Système de fichiers accessible en lecture seulement`

And I also tried to do this manually:

`sudo chmod 666 /snap/code/122/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.css` but I get this error message: "Read-only file system".

Do you know how I can fix that?

Thanks!

**Comment by NoDocCat** [comment]
If you want to write a readonly file, Please use `sudo chmod a+w filename`

**Comment by shalldie** [comment]
### Test about ubuntu

Some friends have tried ubuntu(16.04/22.04) before,
I try 22.04 with `code-server`.

My command is `sudo chmod a+w '/file/path'`, it works well.

### My guess

I found that your path contains `/snap/`, after some simple searches, I felt that it might be related to 'snap'.
It's by design of `snap`, all files are readonly.

### My Suggestions

1. Try another way to install vscode.
2. Or find a way to modify file permissions in snap.

---

Hope it helps.

**Comment by blackbart420** [comment]
Thank you for your help @shalldie and @NoDocCat !!
You were right, Snap was the bad guy.
So I uninstalled VSCode, and then I installed it by downloading the .deb package from the https://code.visualstudio.com/
Now the background extension works fine :)
Thanks again!
