### ISSUE TITLE
Scroll with code 

### ISSUE THREAD

**Issue by rsxdalv** [shalldie/vscode-background#444]
I saw multiple plugins but none of them seem to support this feature - I am interested in having an image that scrolls together with the code, rather than just a static backdrop.

**Comment by suiyun39** [comment]
I roughly know what feature your want, but this feature seems to conflict with the existing feature.

**Comment by rsxdalv** [comment]
Do you have any information about how to implement it?

**Comment by suiyun39** [comment]
First, let me explain how the plugin works：

The plugin add a pseudo-element to vscode using CSS, the pseudo-element‘s width and height is 100% of your edit area window. Next, we add `background-image` to this pseudo-element. Therefore, the background image is fixed in the editing area.

You want the background image to scroll with the code. So, the pseudo-element‘s width and height is 100% of your code's width and height.  Next, we add a background image to this pseudo-element.

If you code scroll, the pseduo-element also scorll.

**Comment by suiyun39** [comment]
We encourage fork this repo and modify it. 

But for some relatively niche features, we have no intention of merge it. We dont't want to introduce too much complexity.

Sorry.
