### ISSUE TITLE
It would really be great if there was an option for random image from the array

### ISSUE THREAD

**Issue by ilmam** [shalldie/vscode-background#93]
So for now, it only shows a specific image from custom image array based on the index. That's great, but what is ever greater, (and I would really appreciate it) is that every time I open a new file, it loads a random image from the array. It would be really awesome!

BTW, thank you for the great job!

**Comment by shalldie** [comment]
vscode's team don't allow to change the background of vscode.

What i do is to edit the vscode's system file,to make it work.Which may cause the appear of a tip:`vscode is broken`.

There is no api to watch a new file's open (i can't use vscode's api), the way to use `setinterval` may consume cpu...
Fun idea, but hard to achieve.

**Comment by ilmam** [comment]
I understand now, thanks for the clarification 👍

**Comment by ilmam** [comment]
Ok, so how about saving the array of custom images in the workspace settings? Is it possible to have different image for different opened projects?

**Comment by sanmaopep** [comment]
It might be possible to achieve random background everytime vscode restart. 
I change getCss.ts locally to get img012 randomly,it seems work well.

**Comment by shalldie** [comment]
Yes,  `random background everytime vscode restart`  is possible.

Instead of hooking css file, i used to use the way to edit entry html file to achieve this.By this way, js can work.

Emm... i've tried before, this is my story:

    I opened this [vscode 1], see the images ,lovely!
    Then i opened the [vscode 2]. What? The order of 2 vscode is the same, then i restart the [vscode 2].
    This time [vscode 2] shows different order of images with [vscode 1], but i still restart it serveral times for a better feel...
    Then the [vscode 3] , i want to it, has the images which [vscode 1] and [vscode 2] don't contains...... wtf , a lot of times to restart , and i was afraid to close thease ...

Sorry for my english , what i want to say is that， it's danger for some obsessions like me , when i got this, i want more.

This is a simple extension, i don't want to add the feature `random background everytime vscode restart` into this.
I think `random background everytime tab/file open`  is funny, but still looking for a good way to achieve. 😸

**Comment by sanmaopep** [comment]
23333,it's danger for me too_(:з」∠)_

**Comment by ilmam** [comment]
Thank you for your support. It's much appreciated, but I still wonder if it's possible to hook the custom images property with workspace settings rather than user settings. Is it possible?

**Comment by shalldie** [comment]
@ilmam 
I don't think it's possible.
Extension changes the vscode's system file, which all instance works with it.
